Add VectorUtil
ProjectKorra/ProjectKorra-Core pull request #8
Opened 2020-07-02 18:53 UTC by Simplicitee

## Changes

### ➕ : Additions 
* Adds VectorUtil class
    * Focuses on implementing Vector functionality that is either complex or not present within Bukkit
* Adds Angle class
    * Allows for easier use of angles within the project without requiring developers to give angle parameters in specific units

## Checklist
- [x] I have tested my changes to the best of my abilities.
- [x] I have linked to any related GitHub Issues or Trello cards.
- [x] I have made sure my code is clean, well documented, and matches the pre-existing style of the codebase.
- [x] I understand that my pull request will only be merged after it is reviewed by maintainers and any requested changes are made.

2020-07-02 23:58 UTC, ChristopherWMM requested changes

2020-07-02 23:58 UTC, ChristopherWMM commented on src/main/java/com/projectkorra/core/math/Angle.java
> +	}
Java is able to implicitly cast `int` and `float` to `double` so I don't think you need anything other than the double typed methods.

2020-07-02 23:58 UTC, ChristopherWMM commented on src/main/java/com/projectkorra/core/util/VectorUtil.java
> +	public static Vector orthogonal(Vector axis, double length, Angle rotation) {
I would prefer that you add the `throws IllegalArgumentException` declaration to the method header that could be caused from the `Validate.isTrue(...)` call. Additionally, it should go in the Javadocs.

2020-07-02 23:58 UTC, ChristopherWMM commented on src/main/java/com/projectkorra/core/util/VectorUtil.java
> +		}
Maybe convert to a ternary assignment?

2020-07-02 23:58 UTC, ChristopherWMM commented on src/main/java/com/projectkorra/core/math/Angle.java
> +package com.projectkorra.core.math;
I think it makes more sense to have this new math directory to be a sub-directory of `util` as opposed to the root source directory.

2020-07-03 07:23 UTC, v-h-gn approved these changes
Everything looks good, I can't say I'd vouch for efficiency but I think this is a good base.

2020-07-03 07:56 UTC, ChristopherWMM commented on src/main/java/com/projectkorra/core/util/VectorUtil.java
> +	 * up or down will return pi/2 or -pi/2 respectively
This line needs to be changed to properly reflect that the method returns the degree value and not the radian value.

2020-07-04 05:58 UTC, ChristopherWMM approved these changes
Looks good :+1:

2020-07-04 06:02 UTC, merged